---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./backendtrafficpolicy.yaml
  - ./externalsecret.yaml
  - ./nodefeaturerule.yaml
  - ./nfs-pvc.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ../../../../templates/volsync
configMapGenerator:
  - name: frigate-configmap
    files:
      - config.yml=./config/config.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
labels:
  - pairs:
      app.kubernetes.io/name: frigate
      app.kubernetes.io/instance: frigate
