---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./miniflux/ks.yaml
  - ./photoprism/ks.yaml
  # - ./plex/ks.yaml
  # - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
