---
# yaml-language-server: $schema=https://raw.githubusercontent.com/envoyproxy/gateway/main/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: home-assistant-timeouts
  namespace: home
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: home-assistant-app
  timeout:
    http:
      requestTimeout: 3600s
      connectionIdleTimeout: 3600s
