---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ha-restarter
  namespace: flux-system
spec:
  targetNamespace: arc-runners
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: actions-runner-controller
    - name: external-secrets-stores
  path: ./kubernetes/apps/arc-runners/ha-restarter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ha-restarter
      namespace: arc-runners
  interval: 30m
  retryInterval: 1m
  timeout: 10m
