---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./amber2mqtt/ks.yaml
  - ./emhass/ks.yaml
  - ./evcc/ks.yaml
  - ./frigate/ks.yaml
  - ./home-assistant/ks.yaml
  - ./home-assistant-v2/ks.yaml
  - ./mosquitto/ks.yaml
  - ./tesla-proxy/ks.yaml
  - ./teslamate/ks.yaml
  - ./zigbee2mqtt/ks.yaml
