---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcpo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: mcpo-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # # Context7 Configuration
        # CONTEXT7_API_KEY: "{{ .CONTEXT7_API_KEY }}"
        # CONTEXT7_BASE_URL: "{{ .CONTEXT7_BASE_URL }}"
        API_KEY: "{{ .MCPO_API_KEY }}"
        config.json: |
          {
            "mcpServers": {
              "memory": {
                "command": "npx",
                "args": ["-y", "@modelcontextprotocol/server-memory"]
              },
              "time": {
                "command": "uvx",
                "args": ["mcp-server-time", "--local-timezone=Australia/Sydney"]
              }
            }
          }

  dataFrom:
    - find:
        path: MCPO_
