---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcpo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: mcpo-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # # Context7 Configuration
        # CONTEXT7_API_KEY: "{{ .CONTEXT7_API_KEY }}"
        # CONTEXT7_BASE_URL: "{{ .CONTEXT7_BASE_URL }}"
        API_KEY: "{{ .MCPO_API_KEY }}"
        config.json: |
          {
            "mcpServers": {
              "memory": {
                "command": "npx",
                "args": ["-y", "@modelcontextprotocol/server-memory"]
              },
              "awslabs.aws-documentation-mcp-server": {
                "command": "uvx",
                "args": ["awslabs.aws-documentation-mcp-server@latest"],
                "env": {
                  "FASTMCP_LOG_LEVEL": "WARNING",
                  "AWS_DOCUMENTATION_PARTITION": "aws",
                  "MCP_USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
                },
                "disabled": false,
                "autoApprove": []
              },
              "sequential-thinking": {
                "command": "npx",
                "args": [
                  "-y",
                  "@modelcontextprotocol/server-sequential-thinking"
                ]
              },
              "brave-search": {
                "command": "npx",
                "args": ["-y", "@brave/brave-search-mcp-server", "--transport", "http"],
                "env": {
                  "BRAVE_API_KEY": "{{ .BRAVE_API_KEY }}"
                }
              },
              "time": {
                "command": "uvx",
                "args": ["mcp-server-time", "--local-timezone=Australia/Sydney"]
              }
            }
          }

  dataFrom:
    - find:
        path: MCPO_
    - find:
        path: BRAVE_
