---
# yaml-language-server: $schema=https://json.schemastore.org/ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blackbox-exporter
  namespace: observability
spec:
  ingressClassName: internal
  rules:
    - host: "blackbox-exporter.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blackbox-exporter
                port:
                  number: 9115
