---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-v2-secrets
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: home-assistant-v2-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TZ: Australia/Sydney
        SECRET_RECORDER_DB_URL: "{{ .HASS_V2_RECORDER_DB_URL }}"
        SECRET_INTERNAL_URL: "{{ .HASS_INTERNAL_URL }}"
        SECRET_EXTERNAL_URL: "{{ .HASS_EXTERNAL_URL }}"
        SECRET_TRUSTED_PROXIES: "{{ .HASS_TRUSTED_PROXIES }}"
        SECRET_PROM_TOKEN: "{{ .HASS_PROM_TOKEN }}"
        SECRET_ZONE_HOME_LATITUDE: "{{ .HASS_HOME_LATITUDE }}"
        SECRET_ZONE_HOME_LONGITUDE: "{{ .HASS_HOME_LONGITUDE }}"
        SECRET_ZONE_HOME_ELEVATION: "{{ .HASS_HOME_ELEVATION }}"
        SECRET_ZONE_OB_PARENTS_LATITUDE: "{{ .HASS_OB_PARENTS_LATITUDE }}"
        SECRET_ZONE_OB_PARENTS_LONGITUDE: "{{ .HASS_OB_PARENTS_LONGITUDE }}"
  dataFrom:
    - find:
        path: HASS_

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-v2-git-secrets
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: home-assistant-v2-git-secrets
    template:
      engineVersion: v2
      data:
        GIT_DEPLOY_KEY: |
          {{ .HASS_CODESERVER_SSH_KEY }}
  data:
    - remoteRef:
        key: HASS_CODESERVER_SSH_KEY
      secretKey: HASS_CODESERVER_SSH_KEY
