---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-systems
resources:
  - ./namespace.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: actions-runner-controller
      app.kubernetes.io/instance: actions-runner-controller
