---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Australia/Sydney"
  CLUSTER_CIDR: "10.69.0.0/16"
  SERVICE_CIDR: "10.96.0.0/16"
  NODE_CIDR: "10.20.0.0/24"
  SVC_K8S_GATEWAY_ADDR: "10.20.0.50"
  SVC_POSTGRES_ADDR: "10.213.0.58"
  SVC_POSTGRES_VECTOR_ADDR: "10.20.0.59"
  SVC_MOSQUITTO_ADDR: "10.20.0.54"
  SVC_PLEX_ADDR: "10.213.0.55"
  SVC_UNIFI_ADDR: "10.213.0.56"
  SVC_HASS_ADDR: "10.20.0.57"
  SVC_HASS_DEV_ADDR: "10.213.0.40"
  SVC_EXTERNAL_INGRESS_ADDR: "10.20.0.53"
  SVC_INTERNAL_INGRESS_ADDR: "10.20.0.52"
  SVC_QBITTORRENT_ADDR: "10.213.0.10"
  SVC_EXTERNAL_GW_ADDR: "10.213.0.53"
  SVC_INTERNAL_GW_ADDR: "10.213.0.52"
