---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-secret
  namespace: arc-runners
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: arc-github-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        github_token: "{{ .ARC_GITHUB_TOKEN }}"
  data:
    - remoteRef:
        key: ARC_GITHUB_TOKEN
      secretKey: ARC_GITHUB_TOKEN
