---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ha-restarter
  namespace: arc-runners
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-runners
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: actions-runner-controller
      namespace: arc-systems
  values:
    githubConfigUrl: "https://github.com/angryninja48/home-assistant-config"
    githubConfigSecret: arc-github-secret
    minRunners: 0
    maxRunners: 1
    template:
      spec:
        initContainers:
          - name: kube-inject
            image: bitnami/kubectl:latest
            command: ["cp", "/opt/bitnami/kubectl/bin/kubectl", "/usr/local/bin/kubectl"]
            volumeMounts:
              - name: kubectl-bin
                mountPath: /usr/local/bin
        serviceAccountName: ha-restarter
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:latest
            volumeMounts:
              - name: kubectl-bin
                mountPath: /usr/local/bin
                readOnly: false
        volumes:
          - name: kubectl-bin
            emptyDir: {}
