---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ha-restarter
  namespace: arc-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ha-pod-restarter
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
    resourceNames: ["home-assistant-v2"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arc-runner-ha-restarter
subjects:
  - kind: ServiceAccount
    name: ha-restarter
    namespace: arc-runners
roleRef:
  kind: ClusterRole
  name: ha-pod-restarter
  apiGroup: rbac.authorization.k8s.io
