---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./backendtlspolicy.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./ocirepository.yaml
  - ../../../../templates/volsync
labels:
  - pairs:
      app.kubernetes.io/name: unifi
      app.kubernetes.io/instance: unifi
