---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb
      version: 4.12.5
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system

  values:

    image:
      repository: "influxdb"
      tag: "2.7.11"

    persistence:
      enabled: true
      existingClaim: influxdb-data

    resources:
      requests:
        memory: 2000Mi
        cpu: 100m
      limits:
        memory: 4000Mi

    # ingress:
    #   enabled: true
    #   tls: true
    #   secretName: influxdb-tls
    #   hostname: &host "influxdb.${SECRET_CLUSTER_DOMAIN}"
    #   annotations:
    #     cert-manager.io/cluster-issuer: letsencrypt-production

    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10

    # config:
    #   opentsdb:
    #     enabled: true
    #   graphite:
    #     enabled: true
    #     database: graphitedb
    #     retention-policy: ""
    #     bind-address: ":2003"
    #     protocol: tcp
    #     consistency-lvel: one
    #     templates:
    #       - "*.app env.service.resource.measurement"
    #       - "servers.* .host.resource.measurement.field*"

    podAnnotations:
      backup.velero.io/backup-volumes: influxdb-data
